name: LinkedIn Mailer

on:
  schedule:
    - cron: "19 4-20/4 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
        env:
          API_KEY_APIFY: "${{ secrets.API_KEY_APIFY }}"
          APIFY_ACTOR_ID: "${{ secrets.APIFY_ACTOR_ID }}"
          RESEND_API_KEY: "${{ secrets.RESEND_API_KEY }}"
          RESEND_EMAIL: "${{ secrets.RESEND_EMAIL }}"
          RESEND_TO_EMAIL: "${{ secrets.RESEND_TO_EMAIL }}"
